name: Genera Documentazione
 
on:
  push:
    branches:
        ["*"]
 
jobs:
  docs:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
 
      - name: Installa Doxygen
        run: sudo apt-get install -y doxygen graphviz
 
      - name: Genera docs
        run: doxygen Doxyfile
 
      - name: Deploy su GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html